from django.urls import path
from . import views

urlpatterns = [
    path('home',views.home, name='home'),
    path('registration', views.accountregistration, name='accountregistration'),
    path('', views.accountlogin, name='accountlogin'),
    path('saveuserregistration', views.saveuserregistration, name='saveuserregistration'),
    path('getlogindata',views.getlogindata,name='getlogindata'),
    path('productall/<str:category>/',views.productall,name='productall'),
    path('fishdet', views.fishdet, name='fishdet'),
    path('fishdetails/<int:fid>/',views.fishdetails,name='fishdetails'),
    path('cart',views.cart,name='cart'),
    path('cart_update', views.cart_update, name='cart_update'),
    path('fish_cart/<int:sid>/',views.fish_cart,name='fish_cart'),
    path('cartdeletedata/<int:cdid>/',views.cartdeletedata,name='cartdeletedata'),
    path('checkoutdetails',views.checkoutdetails,name='checkoutdetails'),
    path('contact',views.contact,name='contact'),
    path('contactdata',views.contactdata,name='contactdata'),
    path('aboutus',views.aboutus,name='aboutus'),
    path('shippingaddr',views.shippingaddr,name='shippingaddr'),
    path('logout',views.logout,name='logout'),
    path('index',views.index,name='index'),
    path('addfish',views.addfish,name='addfish'),
    path('savefishdata', views.savefishdata, name='savefishdata'),
    path('show', views.showdetails, name='showdetails'),
    path('edit/<int:eid>/', views.editbyid, name='editbyid'),
    path('delete/<int:did>/', views.deletebyid, name='deletebyid'),
    path('update/<int:uid>/', views.updatefishdata, name='updatefishdata'),
    path('products',views.products,name='products'),
    path('saveproduct',views.savefishdetals,name='savefishdetals'),
    path('showproduct', views.showproduct, name='showproduct'),
    path('editproduct/<int:eid>/', views.editproductbyid, name='editproductbyid'),
    path('deleteproduct/<int:did>/', views.deleteproductbyid, name='deleteproductbyid'),
    path('updateproduct/<int:uid>/', views.updateproductfishdata, name='updateproductfishdata'),
    path('showorders', views.showorders, name='showorders'),
    ]